config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'

  resources :boards do
    resources :tasks
  end

  resources :tasks do
    resources :comments, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :bigint           not null, primary key
#  content    :text
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
class Board < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  
  def display_created_at
    I18n.l(self.created_at, format: :default)
  end

  def author_name
    user.display_name
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  task_id    :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_comments_on_task_id  (task_id)
#  index_comments_on_user_id  (user_id)
#
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  deadline   :date             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_tasks_on_board_id  (board_id)
#  index_tasks_on_user_id   (user_id)
#
class Task < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :deadline, presence: true

  belongs_to :user
  belongs_to :board
  has_many :comments, dependent: :destroy
  
  has_one_attached :eyecatch
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :comments, dependent: :destroy

  def has_written?(board)
    boards.exists?(id: board.id)
  end

  def display_name
    self.email.split('@').first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @boards = Board.all
  end

  def show
    @tasks = @board.tasks
  end

  def new
    @board = current_user.boards.build
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to boards_path, notice: 'Board is create'
    else
      flash.now[:error] = 'save failure'
      render :new
    end
  end

  def edit
    @board = current_user.boards.find(params[:id])
  end

  def update
    # @board = current_user.boards.build(board_params)
    @board = current_user.boards.find(params[:id])
    if @board.update(board_params)
      redirect_to board_path(@board), notice: 'Board is update'
    else
      flash.now[:error] = 'update failure'
      render :edit
    end
  end

  def destroy
    board = current_user.boards.find(params[:id])
    board.destroy!
    redirect_to root_path, notice: 'succes delete'
  end

  private
  def board_params
    params.require(:board).permit(:title, :content)
  end

  def set_board
    @board = Board.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @task = Task.find(params[:task_id])
    @comment = @task.comments.build
  end

  def create
    task = Task.find(params[:task_id])
    @comment = task.comments.build(comment_params.merge!(user_id: current_user.id))

    if @comment.save
      redirect_to board_task_path(board_id: task.board_id, id: task.id), notice: 'Comment is create'
    else
      flash.now[:error] = 'comment create failure'
      render :new
    end
  end

  private
    def comment_params
        params.require(:comment).permit(:content)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  before_action :authenticate_user!, only:[:new, :create, :edit, :update, :destroy]

  def index
    @task = Task.all
    # boards = Board.find(params[:board_id])
    # @tasks = boards.tasks.all
  end

  def show
    @board = Board.find(params[:board_id])
    @task = @board.tasks.find(params[:id])
#binding.pry
    @comments = @task.comments.all
  end

  def new
    board = Board.find(params[:board_id])
    @task = board.tasks.build
    
  end

  def create
    board = Board.find(params[:board_id])
    @task = board.tasks.build(task_params.merge!(user_id: current_user.id))
    if @task.save
      redirect_to board_path(board), notice: 'Task is create'
    else
      flash.now[:error] = 'save failure'
      render :new
    end
  end

  def edit
    @board = Board.find(params[:board_id])
    @task = @board.tasks.find(params[:id])
  end

  def update
    @board = Board.find(params[:board_id])
    @task = @board.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to board_task_path(@board, @task), notice: 'Task is update'
    else
      flash.now[:error] = 'update failure'
      render :edit
    end
  end

  def destroy
    board = Board.find(params[:board_id])
    task = board.tasks.find(params[:id])
    task.destroy!
    redirect_to board_path(board), notice: 'succes delete'
  end

  private
  def task_params
    params.require(:task).permit(:title, :content, :deadline, :eyecatch)
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_board.html.haml
= link_to board_path(board) do
  .card
    .card_title= board.title
    .card_content= board.content
    .card_info
      .card_icon
        = image_tag 'Oval.png'
        .card_user_info
          %p= board.author_name 
          %p= board.display_created_at
      - if user_signed_in? && current_user.has_written?(board)
        .dropdown
          = image_tag 'Combined Shape'
          .dropdown-content
            = link_to 'edit', edit_board_path(board)
            = link_to 'delete', board_path(board), data: { method: 'delete', confirm: '本当に削除しても大丈夫ですか？' }

app/views/boards/_form.html.haml
.container
  %ul
    - board.errors.full_messages.each do |message|
      %li= message
  = form_with(model: board, local: true) do |f|
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, 'Description' 
    %div
      = f.text_area :content
    = f.submit 'Submit', class: 'btn-primary'

app/views/boards/edit.html.haml
= render 'form', board: @board

app/views/boards/index.html.haml
.container
  %h1 All board
  .boards_list
    - @boards.each do |board|
      = render 'board', board: board
  
  = link_to new_board_path do
    .float_btn
      .float_btn_title
        + All new Board     

app/views/boards/new.html.haml
= render 'form', board: @board

app/views/boards/show.html.haml
.boards_list
  .card
    .card_title= @board.title
    .card_content= @board.content
    .card_info
      .card_icon
        = image_tag 'Oval.png'
        .card_user_info
          %p= @board.author_name 
          %p= @board.display_created_at
      - if user_signed_in? && current_user.has_written?(@board)
        .dropdown
          = image_tag 'Combined Shape'
          .dropdown-content
            = link_to 'edit', edit_board_path(@board)
            = link_to 'delete', board_path(@board), data: { method: 'delete', confirm: '本当に削除しても大丈夫ですか？' }

  - @tasks.each do |task|
    = render 'commons/task', task: task 

  = link_to new_board_task_path(@board) do
    .float_btn
      .float_btn_title
        + All new Card     

app/views/comments/new.html.haml
.container
  %ul
    - @comment.errors.full_messages.each do |message|
      %li= message

  = form_with(model: [@task, @comment], local: true) do |f|
    %div
      = f.label :content, 'New Comment'
    %div
      = f.text_area :content
    

    = f.submit 'Submit', class: 'btn-primary'

app/views/commons/_task.html.haml
.card
  = link_to board_task_path(board_id: @board.id, id: task.id) do
    -if task.eyecatch.attached?
      .card_mark
        = image_tag task.eyecatch
    .card_title
      = task.title
    .card_content
      = task.content
    .card_content
      = task.deadline
    .card_info
      .card_icon
        = image_tag 'Oval.png'
      - if user_signed_in? && current_user.has_written?(@board)
        .dropdown
          = image_tag 'Combined Shape'
          .dropdown-content
            = link_to 'edit', edit_board_task_path(board_id: @board.id, id: task.id)
            = link_to 'delete', board_task_path(board_id: @board.id, id: task.id), data: { method: 'delete', confirm: '本当に削除しても大丈夫ですか？' }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TodoApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
  %body
    %header.header
      .header_title
        = link_to 'Boards', root_path
      - if user_signed_in?
        .dropdown
          = image_tag 'default-avatar.png', class: 'header_avatar dropbtn'
          .dropdown-content
            = link_to 'logout', destroy_user_session_path, data: { method: 'delete' }
      -else
        = link_to 'login', user_session_path,class: 'header_loginBtn'
        .line
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => key}= value
    = yield

app/views/tasks/_form.html.haml
.container
  %ul
    - task.errors.full_messages.each do |message|
      %li= message

  = form_with(model: [@board, task], local: true) do |f|
    %div
      = f.label :eyecatch, 'Image'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :name, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    %div
      = f.label :deadline, 'Dedline'
    %div
      = f.date_field :deadline

    = f.submit 'Submit', class: 'btn-primary'

app/views/tasks/edit.html.haml
= render 'form', task: @task

app/views/tasks/new.html.haml
.container
  %ul
    - @task.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @task, url: board_tasks_path(@task.board), local: true) do |f|
    %div
      = f.label :eyecatch, 'Image'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :name, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    %div
      = f.label :deadline, 'Dedline'
    %div
      = f.date_field :deadline

    = f.submit 'Submit', class: 'btn-primary'

app/views/tasks/show.html.haml
.boards_list
  .board_title-content
    %h2.task_title= @task.title
    - if user_signed_in? && current_user.has_written?(@board)
      .dropdown
        = image_tag 'Combined Shape'
        .dropdown-content
          = link_to 'edit', edit_board_task_path(board_id: @board.id, id: @task.id)
          = link_to 'delete', board_task_path(board_id: @board.id, id: @task.id), data: { method: 'delete', confirm: '本当に削除しても大丈夫ですか？' }
  - if @task.eyecatch.attached?
    .task_eyecatch
      = image_tag @task.eyecatch
  .card
    .card_content
      = @task.content
    .card_content
      = @task.deadline

.comment
  %h2 Comment
  .comment_card
    - @comments.each do |comment|
      .comment_card_content
        = image_tag 'Oval.png'
        %p= comment.content

= link_to new_task_comment_path(@task) do
  .float_btn.mini
    .float_btn_title
      + Add new comment     